spring:
  kafka:
    bootstrap-servers:
        - localhost:9092
    consumer:
      group-id: group
      auto-offset-reset: earliest
      key-deserializer: 'org.apache.kafka.common.serialization.LongSerializer'
      value-deserializer: 'org.springframework.kafka.support.serializer.JsonDeserializer'
      properties:
        spring.json.type.mapping: 'com.aagnone3.springkafka.producer.domain.SourceData:sourceData'
    producer:
      acks: all
      key-serializer: 'org.apache.kafka.common.serialization.LongSerializer'
      value-serializer: 'org.springframework.kafka.support.serializer.JsonSerializer'
      properties:
        spring.json.type.mapping: 'sourceData:com.aagnone3.springkafka.producer.domain.SourceData'

topic:
  name: some-data
  partitions: 3
  replicationFactor: 1